


"use client"
import Script from "next/script"
import { motion } from "framer-motion"
import { Header } from "@/components/marketing/header"
import { Footer } from "@/components/marketing/footer"
import { ChevronDown } from "lucide-react"
import { useState } from "react"

/* ================= FAQ DATA ================= */

const faqData = [
  {
    category: "General",
    items: [
      {
        q: "What is Tecsaro AI?",
        a: "Tecsaro AI is an AEO (Answer Engine Optimization) platform that helps businesses track how visible their brand is in AI-generated answers — across ChatGPT, Gemini, and Perplexity. It crawls your website, runs daily visibility checks, detects competitors in AI answers, and provides recommendations to improve your presence."
      },
      {
        q: "What is AEO?",
        a: "AEO stands for Answer Engine Optimization. It focuses on making your brand and content more likely to appear in answers generated by AI engines like ChatGPT, Gemini, and Perplexity — as opposed to traditional search engine results pages (SERPs)."
      },
      {
        q: "Who is Tecsaro AI for?",
        a: "Tecsaro AI is built for founders, startups, e-commerce businesses, SaaS companies, agencies, consultants, marketing teams, and any business that wants to understand and improve how visible they are in AI-generated answers."
      },
      {
        q: "Do I need any technical knowledge to use Tecsaro AI?",
        a: "No. Tecsaro AI is designed to be clear and action-focused. You get plain-language visibility scores, prompt tracking results, and recommendations you can act on — without needing to be a technical expert."
      },
      {
        q: "Does Tecsaro AI do traditional SEO?",
        a: "Not at this stage. Tecsaro AI is focused exclusively on AEO — helping your brand appear in AI answer engines. We do not currently offer keyword ranking, backlink analysis, or traditional SEO audits."
      }
    ]
  },
  {
    category: "Website Crawling",
    items: [
      {
        q: "What happens when I connect my website?",
        a: "Tecsaro AI crawls your website to extract page content, headings, FAQs, and existing structured data. This information is stored and used to generate relevant prompts and provide accurate AI visibility analysis."
      },
      {
        q: "Which platforms can I connect?",
        a: "You can connect any website by providing the URL. The crawl works across WordPress, Shopify, and custom-built websites."
      },
      {
        q: "Is it safe to connect my website?",
        a: "Yes. Our crawler only reads publicly accessible content on your website — the same content that AI engines and search crawlers can already access. We do not modify your website in any way."
      },
      {
        q: "Can I connect multiple websites?",
        a: "Yes. The number of websites you can connect depends on your plan."
      },
      {
        q: "Can I disconnect my website?",
        a: "Yes. You can disconnect your website at any time from your dashboard."
      }
    ]
  },
  {
    category: "Prompt Generation & Tracking",
    items: [
      {
        q: "What are prompts?",
        a: "Prompts are the questions and queries that real users might type into ChatGPT, Gemini, or Perplexity when looking for businesses, products, or services like yours. Tecsaro AI uses these prompts to check whether your brand appears in the AI-generated answers."
      },
      {
        q: "How are prompts generated?",
        a: "Tecsaro AI automatically generates relevant prompts based on your website content, industry, and business type. You can also add your own custom prompts to track specific queries that matter to your business."
      },
      {
        q: "Can I add my own prompts?",
        a: "Yes. You can add custom prompts at any time to track specific questions or topics relevant to your brand."
      },
      {
        q: "Which AI engines does Tecsaro AI track?",
        a: "We currently track ChatGPT, Gemini, and Perplexity. These are the primary AI answer engines used by consumers and businesses today."
      },
      {
        q: "How often are prompts run?",
        a: "Prompts are run daily across all tracked AI engines, giving you up-to-date visibility data every day."
      }
    ]
  },
  {
    category: "AEO Visibility Score",
    items: [
      {
        q: "What is the AEO Visibility Score?",
        a: "The AEO Visibility Score is a consolidated score that tells you how visible your brand is in AI-generated answers. It is calculated based on brand mentions, position in answers, frequency across prompts, and competitor presence."
      },
      {
        q: "How often is the score updated?",
        a: "The score is updated daily based on fresh prompt tracking results."
      },
      {
        q: "Does a higher score guarantee AI mentions?",
        a: "No. The score reflects your current AI visibility based on tracked prompts and available data. It is a directional metric to help you understand your position and improve over time — not a guarantee of specific placements."
      }
    ]
  },
  {
    category: "Competitor Detection",
    items: [
      {
        q: "How does competitor detection work?",
        a: "When Tecsaro AI runs your prompts across AI engines, it also detects other brands mentioned in the same answers. These are surfaced as potential competitors or brands competing for the same AI answer visibility."
      },
      {
        q: "Can I choose which competitors to track?",
        a: "Yes. You can accept suggestions from Tecsaro AI or manually add competitors you want to monitor."
      },
      {
        q: "What if my competitors are not being detected?",
        a: "You can manually add competitors to your tracking list. Detection is based on what appears in AI answers for your specific prompts."
      }
    ]
  },
  {
    category: "Recommendations & Schema",
    items: [
      {
        q: "What kind of recommendations does Tecsaro AI provide?",
        a: "Recommendations focus on improving your AI answer visibility — such as creating FAQ sections, improving topical authority, adding structured data, and adjusting content structure so AI engines are more likely to cite your brand."
      },
      {
        q: "What is schema generation?",
        a: "Tecsaro AI automatically generates structured schema markup for your pages, including FAQ schema, Organization schema, Article schema, and Product schema where applicable. Structured data helps AI engines understand your content and increases the chance of being cited in answers."
      },
      {
        q: "Does Tecsaro AI publish content or make changes to my website?",
        a: "No. At this stage, Tecsaro AI provides recommendations and generates schema for you to implement. We do not automatically publish or modify your website."
      }
    ]
  },
  {
    category: "Reports & Data",
    items: [
      {
  q: "Can I share my AEO report?",
  a: "Yes. Every plan includes a shareable report link — a public URL you can send to clients or stakeholders. No login required to view it. You can revoke the link at any time from your dashboard."
},
{
  q: "What is Technical Audit?",
  a: "Technical Audit scans your crawled pages for issues that affect AI visibility — missing titles, missing H1s, missing schema markup, thin content, missing canonical tags, and missing image alt text. Free plan shows a 3-page preview. Starter and Pro get all pages."
},
{
  q: "What is AI Citation tracking?",
  a: "AI Citation tracking (Pro only) shows which sources Perplexity cites when answering questions in your category — and whether your brand is one of them. It also surfaces gaps where competitors appear as sources but you don't."
},

      {
        q: "Is my data used to train AI models?",
        a: "No. Your private website data is never used to train public AI models."
      },
      {
        q: "How long is my data stored?",
        a: "Data retention depends on your plan. Contact support@tecsaro.com for details specific to your plan."
      }
    ]
  },
  {
    category: "Pricing & Billing",
    items: [
     
      {
  q: "Is there a free plan?",
  a: "Yes. Tecsaro AI has a free plan that runs forever — no credit card required, no expiry. You get 1 brand, 10 prompts tracked, Gemini visibility, AEO Score, and basic recommendations. Upgrade to Starter or Pro when you need more."
},
      {
        q: "Can I change my plan?",
        a: "Yes. You can upgrade at any time or downgrade at the end of your current billing cycle."
      },
      {
        q: "Do you offer refunds?",
        a: "No. All purchases are final. Since our trial is completely free with no credit card required, you only pay when you actively choose to upgrade. We encourage you to fully explore the platform during your free forever before upgrading."
      },
      {
        q: "What payment methods do you support?",
        a: "UPI, cards, net banking, and international cards via Razorpay."
      }
    ]
  },
  {
    category: "Security & Privacy",
    items: [
      {
        q: "How do you protect my data?",
        a: "We use HTTPS encryption, secure cloud infrastructure, access controls, and regular monitoring to keep your data safe."
      },
      {
        q: "Do you store payment details?",
        a: "No. Payments are processed securely by Razorpay. We never store your card or banking details."
      },
      {
        q: "Can I delete my data?",
        a: "Yes. You can request account and data deletion at any time by contacting support@tecsaro.com."
      }
    ]
  },
  {
    category: "Support",
    items: [
      {
        q: "How can I get support?",
        a: "Email us at support@tecsaro.com. All plans include email support, with priority support for higher-tier plans."
      },
      {
        q: "Where are product updates shared?",
        a: "Updates are shared via email and inside the dashboard."
      }
    ]
  }
]

/* ================= FAQ ITEM ================= */

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false)

  return (
    <div className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm hover:shadow-md transition-shadow duration-200">
      <button
        onClick={() => setOpen(!open)}
        className="w-full flex items-center justify-between px-5 py-4 text-left text-charcoal hover:bg-gray-50 transition-colors"
      >
        <span className="font-medium text-charcoal pr-4">{q}</span>
        <ChevronDown
          className={`h-5 w-5 text-graphite flex-shrink-0 transition-transform duration-200 ${open ? "rotate-180" : ""}`}
        />
      </button>

      {open && (
        <motion.div
          initial={{ opacity: 0, height: 0 }}
          animate={{ opacity: 1, height: "auto" }}
          exit={{ opacity: 0, height: 0 }}
          transition={{ duration: 0.2 }}
          className="px-5 pb-5 border-t border-gray-100"
        >
          <p className="text-graphite text-sm leading-relaxed pt-4">{a}</p>
        </motion.div>
      )}
    </div>
  )
}

/* ================= PAGE ================= */

export default function FAQPage() {
  return (
    <div className="min-h-screen bg-cloud">
 <Script id="schema-faq" type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify({
  "@context": "https://schema.org",
  "@type": "FAQPage",
  name: "Tecsaro AI FAQ — Frequently Asked Questions",
  url: "https://ai.tecsaro.com/faq",
  description: "Answers to common questions about Tecsaro AI, AEO tracking, pricing, and how the platform works.",
  breadcrumb: {
    "@type": "BreadcrumbList",
    itemListElement: [
      { "@type": "ListItem", position: 1, name: "Home", item: "https://ai.tecsaro.com" },
      { "@type": "ListItem", position: 2, name: "FAQ",  item: "https://ai.tecsaro.com/faq" },
    ],
  },
})}} />
      <Header />

      <main className="pt-32 pb-24">
        <div className="container mx-auto px-4 max-w-3xl">

          {/* HERO */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5 }}
            className="text-center mb-16"
          >
            {/* Label */}
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-emerald/10 border border-emerald/20 mb-5">
              <span className="w-2 h-2 rounded-full bg-emerald" />
              <span className="text-sm font-semibold text-emerald tracking-wide uppercase font-mono">FAQ</span>
            </div>

            <h1 className="font-heading text-4xl md:text-5xl font-bold text-charcoal mb-4">
              Frequently Asked Questions
            </h1>
            <p className="text-graphite text-lg max-w-xl mx-auto">
              Everything you need to know about Tecsaro AI and AEO
            </p>
          </motion.div>

          {/* FAQ SECTIONS */}
          <div className="space-y-12">
            {faqData.map((section, si) => (
              <motion.div
                key={section.category}
                initial={{ opacity: 0, y: 24 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true, margin: "-40px" }}
                transition={{ duration: 0.5, delay: si * 0.05 }}
              >
                {/* Category heading */}
                <div className="flex items-center gap-3 mb-5">
                  <h2 className="font-heading text-lg font-bold text-charcoal">
                    {section.category}
                  </h2>
                  <div className="flex-1 h-px bg-gray-200" />
                  <span className="text-xs font-mono text-graphite bg-gray-100 px-2 py-0.5 rounded-full">
                    {section.items.length}
                  </span>
                </div>

                <div className="space-y-3">
                  {section.items.map((item, i) => (
                    <FAQItem key={i} q={item.q} a={item.a} />
                  ))}
                </div>
              </motion.div>
            ))}
          </div>

          {/* CTA */}
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true }}
            transition={{ duration: 0.5 }}
            className="mt-20 text-center bg-white border border-gray-200 rounded-2xl p-10 shadow-sm"
          >
            <p className="text-graphite mb-1 text-sm">Still have questions?</p>
            <p className="font-heading text-xl font-bold text-charcoal mb-4">We're here to help</p>
            <a
              href="mailto:support@tecsaro.com"
              className="inline-flex items-center gap-2 px-6 py-3 bg-emerald text-white rounded-xl font-semibold text-sm hover:bg-emerald-dark transition-colors"
            >
              support@tecsaro.com
            </a>
          </motion.div>

        </div>
      </main>

      <Footer />
    </div>
  )
}